#!/usr/bin/env bash
# Displays username, user id, and home directory from /etc/passwd using while loop

while IFS=: read -r username _ userid _ _ homedir _; do
  echo "${username}:${userid}:${homedir}"
done < /etc/passwd

