#!/usr/bin/env bash
# Prints a story about each user from /etc/passwd parsing fields with while loop and IFS

while IFS=: read -r username password userid groupid desc homedir shell; do
  echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $desc"
done < /etc/passwd

